### ISSUE TITLE
Q:plotting at scale?

### ISSUE THREAD

**Issue by kingjr** [AlexandreAbraham/pynax#10]
Hi @AlexandreAbraham,

Is there a way to easily plot the MRI with their natural scale? At the moment, sklearn uses the `niimg.get_affine()` function; I tried to combine this with your example by adding an `extent` parameter in the display optinos, but it does not work.

Any advice?

Thanks!

**Comment by AlexandreAbraham** [comment]
Hi @kingjr,

By "natural scale", do you mean in the real world coordinate ? Well, there are several ways to do that.

The first one, the easy go, is to use `plot_viz.py` as a basis. If you have a weird affine, you can use nilearn to resample it to a diagonal one and thus have a more accurate display. If your image has 3mm resolution, you can resample it to `np.eye(4) * 3`.

The other way would be to create a view that directly relies on nilearn plotting functions. However, this may require some adaptation of inner pynax code and knowledge of the nilearn plotting function. I could give it a go (I have always postponed that) but not before the end of the week...

Best,

Alex.

**Comment by kingjr** [comment]
Yes, I meant the MRI coordinates in mm, where x=0 is generally in between the two hemispheres.

Maybe I'm missing something? In the `plot_viz.py`, I don't see where such coordinate would be defined.

In nilearn, I think they get the coordinates like this:

```
from nilearn.image.resampling import get_bounds
(xmin, xmax), (ymin, ymax), (zmin, zmax) = get_bounds(niimg.dataobj.shape, niimg.affine)
```

Then you could just use these `xmin`, `xmax` etc as parameters to `imshow`: `plt.imshow(extent=[xmin, xmax, ymin, ymax])`. I gave it a (brief) try, but the refresh got weird, and I got a bit lost in the objects, so I opened the issue to check whether you hadn't designed such things before I try to reinvent the wheel.

**Comment by kingjr** [comment]
I eventually went used a different MRI viewer from nibabel. I'm closing the issue in favour of a [dedicated rep](https://github.com/kingjr/ecoggui)
